name: "List labels"
description: "List labels"

inputs:
  issue-number:
    description: "The number that identifies the issue"
    required: true
  github-token:
    description: "The GitHub token used to create an authenticated client"
    default: ${{ github.token }}
    required: false

outputs:
  labels:
    description: "Labels on the issue"

runs:
  using: 'composite'
  steps:
    - name: List labels
      id: list-labels1
      uses: actions/github-script@v7
      with:
        debug: true
        github-token: ${{ inputs.github-token }}
        result-encoding: 'string'
        script: |
          const result = await github.rest.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ inputs.issue-number }},
          });
          const labels = result.data.map((label) => label.name);
          return labels.join(',');

    - name: Print
      shell: bash
      run: |
        echo ${{ steps.list-labels1.output.labels }}
        echo ${{ steps.list-labels1.output.result }}
