name: Parse Issue Body and Extract Info

on:
  issue_comment:

  issues:
    types:
      - opened
      - edited
      - reopened

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse issue body and extract release info
        uses: actions/github-script@v7
        with:
          script: |
            const issueBody = context.payload.issue.body;

            // 正则表达式解析 release 和版本号
            const releaseRegex = /@ascendbot release (\S+)/;
            const matchRelease = issueBody.match(releaseRegex);
            const release = matchRelease ? matchRelease[1] : 'Not Found';

            // 提取 yml 代码块内容
            const ymlRegex = /```yml\n([\s\S]*?)\n```/;
            const matchYml = issueBody.match(ymlRegex);
            const ymlContent = matchYml ? matchYml[1] : 'No YML found';

            console.log('Release:', release);
            console.log('YML Content:', ymlContent);

            // 在 issue 下添加评论反馈
            const comment = `
              Release: ${release}
              YML Content:
              \`\`\`yaml
              ${ymlContent}
              \`\`\`
            `;

            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.issue.number,
              body: comment
            });

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/releases/')
        with:
          files: Release.txt
